import React from "react";
// import styled from "styled-components";
export const styles = {
  pageContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    minHeight: "100vh",
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    padding: "20px",
    backgroundColor: "#fff",
  },
  headerText: {
    textAlign: "center",
    marginBottom: "30px",
  },
  titleWelcome: {
    color: "#0056D2",
    fontSize: "24px",
    margin: "0",
    fontWeight: "600",
  },
  titleMain: {
    fontSize: "28px",
    margin: "5px 0 0 0",
    fontWeight: "700",
    color: "#333",
  },
  highlight: {
    color: "#FF3333",
  },
  formBox: {
    background: "white",
    border: "1px solid #e0e0e0",
    borderRadius: "8px",
    padding: "30px",
    width: "100%",
    maxWidth: "800px",
    boxShadow: "0 2px 10px rgba(0,0,0,0.05)",
  },
  formRow: {
    display: "flex",
    gap: "20px",
    marginBottom: "20px",
    flexWrap: "wrap", // Added for responsiveness since media queries are hard in inline
  },
  inputGroup: {
    flex: "1",
    display: "flex",
    flexDirection: "column",
    minWidth: "200px", // Ensure they don't squish too much
  },
  label: {
    fontSize: "14px",
    color: "#555",
    marginBottom: "8px",
  },
  inputField: {
    padding: "10px 12px",
    border: "1px solid #ccc",
    borderRadius: "4px",
    fontSize: "14px",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
  },
  mobileInputContainer: {
    display: "flex",
    border: "1px solid #ccc",
    borderRadius: "4px",
    overflow: "hidden",
  },
  mobileCodeSelect: {
    border: "none",
    background: "#fff",
    padding: "10px",
    fontSize: "14px",
    borderRight: "1px solid #eee",
    outline: "none",
  },
  mobileInput: {
    border: "none",
    flex: "1",
    padding: "10px",
    outline: "none",
  },
  passwordWrapper: {
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  inputIconLeft: {
    position: "absolute",
    left: "10px",
    color: "#999",
    zIndex: 1,
  },
  passwordInput: {
    padding: "10px 12px",
    border: "1px solid #ccc",
    borderRadius: "4px",
    fontSize: "14px",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
    paddingLeft: "35px",
  },
  togglePassword: {
    position: "absolute",
    right: "10px",
    cursor: "pointer",
    color: "#555",
    display: "flex",
    alignItems: "center",
    fontSize: "13px",
    gap: "4px",
    userSelect: "none",
  },
  passwordRules: {
    marginTop: "10px",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", // Auto-fit for responsiveness
    gap: "10px",
  },
  ruleItem: {
    fontSize: "13px",
    color: "#777",
    display: "flex",
    alignItems: "center",
  },
  submitBtnWrapper: {
    width: "100%",
    maxWidth: "800px",
    marginTop: "20px",
  },
  submitBtn: {
    backgroundColor: "#FF3333",
    color: "white",
    border: "none",
    padding: "12px 24px",
    borderRadius: "4px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    marginTop: "20px",
  },
  loginLink: {
    marginTop: "15px",
    fontSize: "14px",
    color: "#333",
  },
  linkAnchor: {
    color: "#0056D2",
    textDecoration: "none",
    marginLeft: "5px",
  },
};